name: "run flake checks"
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
        with:
          # Shallow clones won't work
          fetch-depth: 0
      - uses: cachix/install-nix-action@v12
        with:
          install_url: https://github.com/numtide/nix-flakes-installer/releases/download/nix-2.4pre20210415_76980a1/install
          extra_nix_config: |
            experimental-features = nix-command flakes
            access-tokens = github.com:${{ secrets.NIX_GITHUB_TOKEN }}
      - name: validate root devShell
        run: nix develop -c echo "PASSED"
      - name: validate formatting of all files
        run: nix develop -c treefmt --fail-on-change
      - name: build all flake templates on macOS and linux
        run: nix develop -c checks
